name: Server API Deploy

on:
  push:
    branches: [ feat/server ]
  pull_request:
    branches: [ feat/server ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo feat/server branch
      uses: actions/checkout@v2
      with:
          repository: mohanzeal/product-comparison
          ref: feat/server
          token: ${{ secrets.CP_PROD_DEPLOY }}
    
    - name: Get yarn cache directory path
      id: yarn-cache-server-folder
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - name: Cache Yarn server node_modules
      uses: actions/cache@v2
      id: yarn-cache-server
      with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-server-folder.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn install --immutable

    - name: lint all server dependent packages
      run: yarn server:lint

    - name: test all server dependent packages
      run: yarn server:test

    - name: build all server dependent packages
      run: yarn server:build
    
    - name: export to static site
      run: yarn server:export

    - name: Deploy to EC2 server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_NODE_SSH_KEY }}
        SOURCE: "./build/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
