name: Server API Deploy

on:
  push:
    branches: [ feat/server ]
  pull_request:
    branches: [ feat/server ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo feat/server branch
      uses: actions/checkout@v2
      with:
          repository: mohanzeal/product-comparison
          ref: feat/server
          token: ${{ secrets.CP_PROD_DEPLOY }}
    
    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@master
      id: ssm
      with:
        aws-region: 'ap-south-1'
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: 'i-06b826c5b66f5fe8e'

        working-directory: /home/ec2-user/apps/product-comparison
        command: ls -al
        comment: Hello world!
