name: Deploy Serverless

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: 'us-east-1'

    steps:
    - name: Check out repo dev branch
      uses: actions/checkout@v2
      with:
          repository: mohanzeal/product-comparison
          ref: dev
          token: ${{ secrets.CP_PROD_DEPLOY }}

    - uses: actions/setup-node@v1
      with:
        node-version: 17.2.0

    - name: Install Yarn
      run: npm install -g yarn serverless@2.72.2

    - name: Install dependencies
      run: yarn install

    - name: Run lint
      run: yarn lint

    - name: Run tests
      run: yarn test

#     - name: Download `.serverless` state from S3
#       run: aws s3 sync s3://aws-serverless-config-files/comparablez-frontend/prod/.serverless packages/comparablez/.serverless --delete 

    - name: Deploy to AWS
      run: cd packages/comparablez && yarn deploy

    - name: Upload `.serverless` state to S3
      run: aws s3 sync packages/comparablez/.serverless s3://aws-serverless-config-files/comparablez-frontend/prod/ --delete 
