name: Deploy Serverless

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: 'us-east-1'
      SPACE_ID: ${{secrets.SPACE_ID}}
      ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
      SITE_URL: ${{secrets.SITE_URL}}
      NEXT_PUBLIC_GA_ID: ${{secrets.NEXT_PUBLIC_GA_ID}}
      NEXTJS_REVALIDATE_INTERVAL: ${{secrets.NEXTJS_REVALIDATE_INTERVAL}}
      

    steps:
    - name: Check out repo master branch
      uses: actions/checkout@v2
      with:
          repository: mohanzeal/product-comparison
          ref: master
          token: ${{ secrets.CP_PROD_DEPLOY }}

    - name: Cache Yarn root node_modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - uses: actions/setup-node@v1
      with:
        node-version: 17.2.0

    - name: Install Yarn
      run: npm install -g yarn serverless@2.72.2

    - name: Install dependencies
      run: yarn install

    - name: Run lint on all packages
      run: yarn lint

    - name: Run tests on all packages
      run: yarn test
    
    - name: Run Build on all packages
      run: yarn build

    - name: Download `.serverless` state from S3
      run: aws s3 sync s3://aws-serverless-config-files/comparablez-frontend/prod/.serverless packages/comparablez/.serverless --delete 

    - name: Deploy to AWS
      run: cd packages/comparablez && yarn deploy

    - name: Upload `.serverless` state to S3
      run: aws s3 sync packages/comparablez/.serverless s3://aws-serverless-config-files/comparablez-frontend/prod/ --delete 
