name: Deploy Serverless

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
          repository: mohanzeal/product-comparison
          token: ${{ secrets.cp_deploy }}
